train:
  training:
    device: cuda
    gpu:
      enabled: true
      visible_devices: "0"
      max_num_gpus: 1
      memory_fraction: 0.80
      allow_tf32: true
      cudnn_benchmark: true
      empty_cache_on_start: true
      log_gpu_info: true
      fail_if_cuda_unavailable: true

  dataset:
    repo_id: local/pick-place-demo-dual-arm-v1
    root: /home/hb/isaac_teleop_flexiv_inspire/sessions/pick_place_demo/lerobot_merged/dual_arm_lerobot_v1
    video_backend: pyav
    skip_bad_video_samples: false

  env: null
  policy:
    type: act
    config_path: /home/hb/isaac_teleop_flexiv_inspire/config/policies/pick_place_act_train_policy.yaml

  output_dir: /home/hb/isaac_teleop_flexiv_inspire/artifacts/policies/pick_place_demo_act_v1
  job_name: pick_place_demo_act_v1
  resume: false
  seed: 1000
  num_workers: 0
  batch_size: 8
  steps: 10000
  eval_freq: 0
  log_freq: 50
  save_checkpoint: true
  save_freq: 1000
  use_policy_training_preset: true

  eval:
    n_episodes: 1
    batch_size: 1

  wandb:
    enable: false
    disable_artifact: true
    project: lerobot_flexiv_inspire
    log_only_loss: true
    mode: disabled
